# Generated by Django 5.2.3 on 2025-06-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('現場グッズ', '現場グッズ'), ('参戦服', '参戦服'), ('宿泊用品', '宿泊用品')], default='現場グッズ', max_length=50),
        ),
    ]
