# Generated by Django 5.2.3 on 2025-06-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_itemlist_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
