# Generated by Django 5.2.3 on 2025-06-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_checklistitem_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
