# Generated by Django 5.2.3 on 2025-06-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
